### ISSUE TITLE
possible attachment export issue?

### ISSUE THREAD

**Issue by quite** [tbvdm/sigtop#15]
I'm getting a couple of `sigtop: Missing attachment path` when exporting attachments. I tried to get hold of exactly which message it was, adding the below code. But in the output group at that time there is no message as all, let alone any attachment... Maybe my code is faulty. It would be nice to see exactly where the missing attachment path occurs. But also perhaps you know for a fact that there really isn't anything of importance missing? Or at least not anything which can be dug out. And the warning message could thus be ignored?

```
diff --git a/cmd-export-attachments.c b/cmd-export-attachments.c
index 6cb913e..ab5dfa2 100644
--- a/cmd-export-attachments.c
+++ b/cmd-export-attachments.c
@@ -222,6 +222,14 @@ export_attachment_list(struct sbk_ctx *ctx, struct sbk_attachment_list *lst,

        TAILQ_FOREACH(att, lst, entries) {
                if ((src = sbk_get_attachment_path(ctx, att)) == NULL) {
+                       struct tm *tm;
+                       time_t tt = att->time_sent / 1000;
+                       if ((tm = localtime(&tt)) == NULL) {
+                               warnx("localtime() failed");
+                       } else {
+                               printf("%d-%02d-%02d %02d:%02d:%02d %d\n", tm->tm_year + 1900, tm->tm_mon, tm->tm_mday,
+                                      tm->tm_hour, tm->tm_min, tm->tm_sec, att->size);
+                       }
                        ret = -1;
                        continue;
                }
@@ -317,6 +325,14 @@ export_conversation_attachments(struct sbk_ctx *ctx,
                goto out;

        ret = export_attachment_list(ctx, lst, cnv_dfd, mode);
+       if (ret < 0) {
+               if (cnv->recipient->group != NULL) {
+                       printf("convo group: %s\n", cnv->recipient->group->name);
+               }
+               if (cnv->recipient->contact != NULL) {
+                       printf("convo contact: %s\n", cnv->recipient->contact->name);
+               }
+       }
        close(cnv_dfd);

 out:
```

**Comment by tbvdm** [comment]
> But in the output group at that time there is no message as all, let alone any attachment... Maybe my code is faulty.

There's a small mistake in how you print the dates: `tm_mon` has range 0–11, not 1–12. If you replace `tm->tm_mon` with `tm->tm_mon + 1`, you'll see the right dates.

> It would be nice to see exactly where the missing attachment path occurs.

I'm thinking of committing this:

```
diff --git a/sbk-attachment.c b/sbk-attachment.c
index 3601d7e..ac76e94 100644
--- a/sbk-attachment.c
+++ b/sbk-attachment.c
@@ -16,6 +16,7 @@
 
 #include <sys/types.h>
 
+#include <inttypes.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
@@ -221,7 +222,8 @@ sbk_get_attachment_path(struct sbk_ctx *ctx, struct sbk_attachment *att)
 	char *path;
 
 	if (att->path == NULL) {
-		warnx("Missing attachment path");
+		warnx("Missing attachment path (sent %" PRIu64 ")",
+		    att->time_sent);
 		return NULL;
 	}
 
```

You can then search for the timestamp in the JSON output. For example, if you have `jq` installed:

```
$ sigtop att -l att
sigtop: Missing attachment path (sent 1234567890123)
$ sigtop msg -f json json
$ jq '.[] | select(.sent_at == 1234567890123)' json/* | less
```

> But also perhaps you know for a fact that there really isn't anything of importance missing? Or at least not anything which can be dug out. And the warning message could thus be ignored?

The `Missing attachment path` warning means that an attachment cannot be exported because it doesn't exist in the Signal Desktop directory. One possible reason for this is that the attachment simply wasn't downloaded by Signal. But I'm not sure if there might be other reasons as well.

If possible, could you take a look at the JSON output for messages with missing attachments and see if those attachments have a `downloadJobId` attribute? The presence of that attribute probably means the attachment wasn't downloaded.

**Comment by quite** [comment]
Wow, thanks! I had 2 `Missing attachment path`, and now I found both in Signal Desktop. They were simply not downloaded. 

One of them had the downloadJobId, and the other didn't. I clicked on the blurred images to have them downloaded, but got nothing (literally -- 1 see emoji-reactions floating in space for one of them). They were sent some 5 months ago so.

Perhaps the warning could say something about non-downloaded attachments? And/or in the README along with jq tip

**Comment by tbvdm** [comment]
Glad you were able to locate the messages. Undelivered messages and attachments are retained on the Signal server for a limited time only, so that's probably why you can't download the attachments anymore.

I'll improve the warning and see if there's a good way to mention `jq` somewhere in the README. Good ideas, thanks!

**Comment by quite** [comment]
Thanks! That's an improvement. Now I can use grep to remove specific, known harmless instances of the warning when i run sigtop :)
